#ifndef CLASSPARSER_GLOBAL_H
#define CLASSPARSER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CLASSPARSER_LIBRARY)
#  define CLASSPARSERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define CLASSPARSERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CLASSPARSER_GLOBAL_H
