#ifndef TEXTEDITOR_GLOBAL_H
#define TEXTEDITOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TEXTEDITOR_LIBRARY)
#  define TEXTEDITORSHARED_EXPORT Q_DECL_EXPORT
//#else
//#  define TEXTEDITORSHARED_EXPORT Q_DECL_IMPORT
#else
#  define TEXTEDITORSHARED_EXPORT
#endif

#endif // TEXTEDITOR_GLOBAL_H
